import { useState } from 'react';
import { GEOGRAPHY_LESSONS, REGION_COMPARISON } from '../../../shared/geographyLessons.js';
import { mapProvinceNote } from '../../../shared/provinces.js';
export default function GeographyLesson({ map }) {
  const lesson = GEOGRAPHY_LESSONS[map.id]; const [step, setStep] = useState(0), [answer, setAnswer] = useState(null);
  if (!lesson) return null;
  return <section className="geography-lesson" aria-label={`Bài học địa lý ${map.name}`}><span className="eyebrow">TRẠM KIẾN THỨC · 3 PHÚT KHÁM PHÁ</span><h3>Hiểu miền đất vừa đi qua</h3><p className="lesson-region">{lesson.region}</p><nav aria-label="Các phần bài học">{['Vị trí & địa hình','Khí hậu & thời tiết','Liên hệ & ghi nhớ'].map((label, index) => <button key={label} aria-pressed={index === step} onClick={() => setStep(index)}><b>0{index + 1}</b>{label}</button>)}</nav><div className="lesson-body" aria-live="polite">
    {step === 0 && <><h4>Địa danh này nằm ở đâu?</h4><p>{lesson.location}</p><h4>Địa hình ảnh hưởng thế nào?</h4><p>{lesson.terrain}</p><p className="province-context">{mapProvinceNote(map.id)}</p></>}
    {step === 1 && <><h4>Nhịp thời tiết theo mùa</h4><p>{lesson.climate}</p><p className="lesson-definition"><strong>Phân biệt:</strong> thời tiết là nắng, mưa, nhiệt độ trong thời gian ngắn; khí hậu là đặc điểm khái quát qua nhiều năm. Bài học mô tả khí hậu, không phải dự báo hôm nay.</p><div className="lesson-regions">{REGION_COMPARISON.map(([name, text]) => <article key={name}><strong>{name}</strong><p>{text}</p></article>)}</div></>}
    {step === 2 && <><h4>Từ địa lý đến lịch sử và đời sống</h4><p>{lesson.connection}</p><p className="lesson-takeaway">✦ {lesson.takeaway}</p><fieldset><legend>{lesson.question}</legend>{lesson.choices.map((choice, index) => <button key={choice} disabled={answer !== null} className={answer !== null && index === lesson.answer ? 'correct' : answer === index ? 'incorrect' : ''} onClick={() => setAnswer(index)}>{'ABC'[index]}. {choice}</button>)}</fieldset>{answer !== null && <p role="status">{answer === lesson.answer ? 'Đúng rồi! ' : 'Cùng ghi nhớ nhé: '}{lesson.explanation}</p>}<small>Câu củng cố giúp ghi nhớ, không thay đổi điểm lượt chạy.</small></>}
    </div><div className="lesson-controls"><button className="outline-button" disabled={step === 0} onClick={() => setStep(step - 1)}>← Phần trước</button><span>{step + 1}/3</span><button className="outline-button" disabled={step === 2} onClick={() => setStep(step + 1)}>Phần tiếp →</button></div><details className="lesson-sources"><summary>Nguồn đọc thêm</summary>{lesson.sources.map(([label, url]) => <a className="source-link" key={url} href={url} target="_blank" rel="noreferrer">{label} ↗</a>)}<p>Bài học tự biên soạn, giải thích khái quát và gợi ý liên hệ. Mùa và thời tiết thực tế có thể thay đổi theo địa hình, từng năm.</p></details></section>;
}
