import { useState, lazy, Suspense } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { EXPLORATION_MAPS } from '../../../shared/exploration.js';
import { provinceNote } from '../../../shared/provinces.js';
import { api } from '../services/api.js';
import { ExamResult } from '../components/Exam.jsx';
import CharacterPicker from '../components/CharacterPicker.jsx';
import { readStorage, writeStorage } from '../services/storage.js';
const ProvinceRun = lazy(() => import('../components/ProvinceRun.jsx'));
export default function Explore() {
 const [params] = useSearchParams(), map = EXPLORATION_MAPS.find(p => p.id === params.get('province'));
 const [username,setUsername] = useState(() => readStorage('username','Nhà thám hiểm'));
 const [run, setRun] = useState(null), [result, setResult] = useState(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [pendingAnswers, setPendingAnswers] = useState(null), [character, setCharacter] = useState(() => readStorage('characterId','ty-nam'));
 if (!map) return <section className="content-page"><h1>Chọn một tỉnh/thành để bắt đầu</h1><Link to="/maps">Mở bản đồ Việt Nam →</Link></section>;
 async function start() { setBusy(true); setError(''); try { setRun(await api.startExam({ mode:'explore', provinceId:map.id, count:10 })); setResult(null); setPendingAnswers(null); writeStorage('characterId',character); writeStorage('username',username.trim() || 'Nhà thám hiểm'); } catch(e) { setError(e.message); } finally { setBusy(false); } }
 async function finish(answers) { setPendingAnswers(answers); setBusy(true); setError(''); try { const data = await api.submitExam(run.token,{answers}); setResult(data); const progress = readStorage('provinceProgress',{}); writeStorage('provinceProgress',{...progress,[map.id]:{mark:data.mark,date:Date.now()}}); } catch(e) { setError(e.message); } finally { setBusy(false); } }
 return <section className="content-page"><Link className="back-link" to="/maps">← Bản đồ Việt Nam</Link><div className="page-intro"><span className="eyebrow">KHÁM PHÁ VIỆT NAM · MAP {map.number}</span><h1>{map.name}</h1><p>{provinceNote(map.name,'34')}</p><p>10 câu ngẫu nhiên về địa bàn hiện nay và những tỉnh/thành cũ thuộc địa bàn này.</p></div>{result ? <><ExamResult result={result} title={map.name} onRestart={() => {setRun(null);setResult(null);}}/><section className="exam-summary"><h2>Ghi nhớ miền đất vừa qua</h2><p>{map.name} · {map.region}. Địa hình: {map.terrain.toLowerCase()}. Sông nước tiêu biểu: {map.water}. Điểm tìm hiểu: {map.landmark}.</p><p>{map.region === 'Miền Bắc' ? 'Khí hậu miền Bắc có mùa đông lạnh hơn và mùa hè nóng, mưa nhiều; độ cao và hướng núi tạo khác biệt giữa các điểm.' : map.region === 'Miền Trung' ? 'Miền Trung có khí hậu phân hóa mạnh giữa cao nguyên và ven biển. Mùa mưa, gió mùa và bão cần được xét theo từng tiểu vùng; không dùng một kiểu thời tiết cho cả tỉnh.' : 'Nam Bộ nhìn chung nóng quanh năm, phân biệt mùa mưa và mùa khô. Ở vùng thấp cần chú ý ngập, triều và xâm nhập mặn theo mùa.'}</p><a href="https://vietnam.travel/things-to-do/weather-and-climate-vietnam" target="_blank" rel="noreferrer">Tham khảo khí hậu các vùng ↗</a></section></> : run ? <Suspense fallback={<p>Đang chuẩn bị cung chạy…</p>}><ProvinceRun key={run.token} run={run} map={map} characterId={character} username={username.trim() || 'Nhà thám hiểm'} onFinish={finish}/></Suspense> : <><figure className="destination-preview"><img src={map.scenery.url} alt={`Cảnh chạy ${map.scenery.name}`}/><figcaption><strong>{map.scenery.name}</strong><span>{map.scenery.oldProvince !== map.name ? `${map.scenery.oldProvince} trước sáp nhập · nay thuộc ${map.name}` : map.name} · Minh họa cách điệu</span></figcaption></figure><label className="setup-fields">Tên nhân vật<input value={username} maxLength={24} onChange={e=>setUsername(e.target.value)}/></label><p>Khởi đầu với 3 mạng trống đồng. Trả lời đúng hồi 1 mạng và tiến 20 m; sai mất 1 mạng và lùi 50 m.</p><CharacterPicker value={character} onChange={setCharacter}/><button className="primary-button" disabled={busy} onClick={start}>{busy ? 'Đang chuẩn bị…' : 'Chạy khám phá · 10 câu →'}</button></>}{busy && pendingAnswers && <p role="status">Đang chấm bài…</p>}{error && <div className="inline-error" role="alert">{error}{pendingAnswers && <button className="outline-button" disabled={busy} onClick={() => finish(pendingAnswers)}>Gửi lại đáp án</button>}</div>}</section>;
}
