import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { api } from '../services/api.js';
export default function Leaderboard() {
  const [params, setParams] = useSearchParams(); const ranked = params.get('mode') === 'mixed';
  const [metric, setMetric] = useState('score'), [rows, setRows] = useState([]), [status, setStatus] = useState('loading'), [retry, setRetry] = useState(0);
  useEffect(() => { const controller = new AbortController(); setStatus('loading'); api.leaderboard(metric, controller.signal, ranked ? 'mixed' : undefined).then(data => { setRows(data); setStatus('ready'); }).catch(() => { if (!controller.signal.aborted) setStatus('error'); }); return () => controller.abort(); }, [metric, retry, ranked]);
  const field = { score: 'highScore', distance: 'totalDistance', knowledge: 'correctAnswers' }[metric];
  return <section className="content-page"><div className="page-intro"><div className="eyebrow">CÙNG NHAU ĐI XA HƠN</div><h1>Những bước chân dẫn đầu<span>.</span></h1><p>Mỗi hành trình đều đáng nhớ. Khám phá thành tích của cộng đồng HisRun.</p></div><div className="tab-row"><button aria-pressed={!ranked} onClick={() => setParams({})}>Tất cả lượt chơi</button><button aria-pressed={ranked} onClick={() => setParams({mode: 'mixed'})}>Thi tổng hợp</button></div><div className="tab-row">{[['score', 'Điểm cao'], ['distance', 'Quãng đường'], ['knowledge', 'Kiến thức']].map(([id, name]) => <button className={metric === id ? 'active' : ''} aria-pressed={metric === id} key={id} onClick={() => setMetric(id)}>{name}</button>)}</div>{status === 'loading' ? <p role="status" className="empty-state">Đang tải bảng xếp hạng…</p> : status === 'error' ? <div className="empty-state"><h2>Chưa kết nối được bảng xếp hạng</h2><p>Kết quả trên thiết bị của bạn vẫn được giữ nguyên.</p><button className="outline-button" onClick={() => setRetry(retry + 1)}>Thử lại</button></div> : rows.length === 0 ? <div className="empty-state"><h2>Hãy để lại dấu chân đầu tiên</h2><p>Hoàn thành một lượt chạy để xuất hiện tại đây.</p><Link className="primary-button" to="/game">Chạy ngay →</Link></div> : <div className="leaderboard-table"><div className="leaderboard-row table-heading"><span>HẠNG</span><span>NHÀ THÁM HIỂM</span><span>{metric === 'score' ? 'ĐIỂM CAO' : metric === 'distance' ? 'TỔNG MÉT' : 'CÂU ĐÚNG'}</span></div>{rows.map((row, index) => <div className="leaderboard-row" key={row._id}><span className={index < 3 ? 'podium' : ''}>{String(index + 1).padStart(2, '0')}</span><strong>{row.username || 'Nhà thám hiểm'}</strong><strong>{(row[field] || 0).toLocaleString('vi-VN')}</strong></div>)}</div>}<p className="scope-note">Bảng xếp hạng thử nghiệm. Điểm do thiết bị gửi, đã kiểm tra giới hạn nhưng chưa xác minh toàn bộ lượt chơi.</p></section>;
}
