import { useState } from 'react';
import { Link } from 'react-router-dom';
import MapArt from '../components/MapArt.jsx';
import { JOURNEY_MAPS, SCHOOL_LEVELS } from '../../../shared/journey.js';
import { readStorage, writeStorage } from '../services/storage.js';
export default function Maps() {
  const [school, setSchool] = useState(() => readStorage('schoolLevel', 'primary'));
  const progress = readStorage('journeyProgress', {});
  const complete = JOURNEY_MAPS.filter(map => progress[`${school}:${map.id}`]).length;
  function selectSchool(value) { setSchool(value); writeStorage('schoolLevel', value); }
  return <section className="maps-page"><div className="page-intro"><div className="eyebrow">BẮC → TRUNG → NAM · CHƯƠNG TRÌNH TRƯỚC 2018</div><h1>Mỗi miền đất.<br/>Một câu chuyện<span>.</span></h1><p>Từ núi rừng Pác Bó đến Bến Nhà Rồng. Chạy qua địa danh, tìm hiểu dấu mốc lịch sử và khám phá địa lý ngay trên hành trình.</p></div><div className="journey-layout"><aside className="journey-sidebar"><span className="eyebrow">CHỌN CẤP HỌC</span><div className="school-options">{SCHOOL_LEVELS.map(level => <button key={level.id} className={school === level.id ? 'selected' : ''} aria-pressed={school === level.id} onClick={() => selectSchool(level.id)}><strong>{level.name}</strong><span>{level.detail}</span></button>)}</div><div className="passport"><span>HỘ CHIẾU HÀNH TRÌNH</span><strong>{complete}<small> / {JOURNEY_MAPS.length}</small></strong><p>map đã hoàn thành ở cấp học này</p><progress aria-label="Số map đã hoàn thành" max={JOURNEY_MAPS.length} value={complete}/></div><p className="route-hint">Bạn có thể bắt đầu từ Map 1 hoặc chọn một địa điểm yêu thích. Về đích để tiếp tục tới map kế tiếp.</p></aside><div className="map-route"><div className="route-direction">BẮT ĐẦU TỪ PHÍA BẮC ↓</div><div className="map-grid">{JOURNEY_MAPS.map(map => <article className="map-card" key={map.id}><div className="map-card-art"><MapArt map={map}/><span className="map-number">MAP {map.number}</span>{progress[`${school}:${map.id}`] && <span className="map-complete">✓ Đã đến</span>}</div><div className="map-card-body"><span className="map-region">{map.region} · {map.distance} m</span><h2>{map.name}</h2><p className="map-title">{map.title}</p><div className="landmark-chips">{map.landmarks.map(place => <span key={place.id}>⌖ {place.name}</span>)}</div><Link className="map-play" to={`/game?map=${map.id}&school=${school}`}>Vào Map {map.number} <span>↗</span></Link></div></article>)}</div><div className="route-direction route-end">ĐIỂM ĐẾN PHÍA NAM · TP. HỒ CHÍ MINH ✦</div></div></div><details className="curriculum-note"><summary>Về kiến thức và chương trình SGK cũ</summary><p>Chủ đề định hướng theo chương trình trước 2018. Cấp 1 tập trung kiến thức cơ bản lớp 4–5; cấp 2 và cấp 3 tăng mức độ nhận biết, liên hệ và vận dụng. Địa danh và cách phân vùng trong câu hỏi dùng bối cảnh thời kỳ đó, không dùng để tra địa giới hiện hành.</p><p>54 câu được tự biên soạn, có nguồn từ cơ quan di sản, bảo tàng và UNESCO. Chưa đối chiếu từng bài với một ấn bản SGK cụ thể; nguồn xuất hiện sau khi trả lời. Chọn cấp học là mức độ gợi ý, không phải cam kết phân phối chương trình từng lớp.</p></details></section>;
}
