import { useState } from 'react';
import { Link } from 'react-router-dom';
import AdministrativeMap from '../components/AdministrativeMap.jsx';
import { EXPLORATION_MAPS } from '../../../shared/exploration.js';
import { provinceNote } from '../../../shared/provinces.js';
import { readStorage } from '../services/storage.js';
export default function Maps() {
 const [region, setRegion] = useState('Tất cả'), [search, setSearch] = useState('');
 const progress = readStorage('provinceProgress', {});
 return <section className="content-page maps-page"><div className="page-intro"><span className="eyebrow">KHÁM PHÁ VIỆT NAM</span><h1>34 tỉnh thành.<br/>Mỗi nơi một bài học.</h1><p>Chọn trên bản đồ hoặc danh sách từ Bắc vào Nam. Mỗi map có 10 câu ngẫu nhiên chỉ thuộc địa phương đó, kể cả các tỉnh cũ nay được sáp nhập vào.</p></div><AdministrativeMap/><section className="province-directory"><div className="section-heading"><h2>Chọn map khám phá</h2><span>{Object.keys(progress).filter(id => EXPLORATION_MAPS.some(p => p.id === id)).length}/34 map đã hoàn thành</span></div><label className="exam-name">Tìm tỉnh/thành hiện nay hoặc trước sáp nhập<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Ví dụ: Bình Dương, Hà Nội…"/></label><div className="region-options">{['Tất cả','Miền Bắc','Miền Trung','Miền Nam'].map(r => <button key={r} aria-pressed={region === r} onClick={() => setRegion(r)}>{r}</button>)}</div><div className="map-grid">{EXPLORATION_MAPS.filter(p => (region === 'Tất cả' || p.region === region) && `${p.name} ${p.members.join(' ')}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))).map(p => <article className="map-card province-card" key={p.id}><span className="eyebrow">MAP {p.number} · {p.region}</span><h2>{p.name}</h2><img className="province-scenery-thumbnail" src={p.scenery.url} alt={`Cảnh chạy ${p.scenery.name}`} loading="lazy"/><strong>⌖ {p.scenery.name}</strong><p>{provinceNote(p.name,'34')}</p><p>10 câu mỗi lượt · {progress[p.id] ? `Đã hoàn thành ${progress[p.id].mark}/10` : 'Sẵn sàng khám phá'}</p><Link className="primary-button" to={`/explore?province=${p.id}`}>Vào Map {p.number} →</Link></article>)}</div></section><p className="scope-note">Mỗi tỉnh/thành có một cảnh chạy riêng lấy cảm hứng từ danh thắng địa phương. Hình ảnh được cách điệu cho trò chơi; ngân hàng câu hỏi tiếp tục được bổ sung.</p><Link className="outline-button" to="/legacy-maps">Xem lại 8 cung chạy địa danh trước đây →</Link></section>;
}
