import { getProvinceScenery } from './provinceScenery.js';
import { PROVINCES } from './provinces.js';
// Historical names remain in the landmark field; the enclosing map uses 2025 units.
const rows = [
 ['caobang','Miền Bắc','Pác Bó','Cao Bằng','Di tích cách mạng','Núi đá vôi','Sông Bằng','map-01',22.7],
 ['tuyenquang','Miền Bắc','Tân Trào','Tuyên Quang','Di tích cách mạng','Miền núi','Sông Lô','map-01',22.3],
 ['laocai','Miền Bắc','Ruộng bậc thang Mù Cang Chải','Yên Bái','Cảnh quan nông nghiệp','Miền núi','Sông Hồng','map-01',22.1],
 ['laichau','Miền Bắc','Pu Ta Leng','Lai Châu','Núi cao','Miền núi','Sông Đà','map-01',22],
 ['dienbien','Miền Bắc','Đồi A1','Điện Biên','Di tích chiến trường','Lòng chảo và núi','Sông Nậm Rốm','map-02',21.8],
 ['langson','Miền Bắc','Ải Chi Lăng','Lạng Sơn','Di tích chiến trường','Miền núi','Sông Kỳ Cùng','map-01',21.7],
 ['thainguyen','Miền Bắc','ATK Định Hóa','Thái Nguyên','Di tích cách mạng','Trung du và núi','Sông Cầu','map-01',21.6],
 ['sonla','Miền Bắc','Nhà tù Sơn La','Sơn La','Di tích lịch sử','Miền núi','Sông Đà','map-01',21.3],
 ['phutho','Miền Bắc','Đền Hùng','Phú Thọ','Di tích thờ tự','Trung du và núi','Sông Lô','map-05',21.2],
 ['bacninh','Miền Bắc','Đền Đô','Bắc Ninh','Di tích thờ tự','Đồng bằng và trung du','Sông Cầu','map-05',21.1],
 ['quangninh','Miền Bắc','Vịnh Hạ Long','Quảng Ninh','Di sản thiên nhiên','Núi và ven biển','Biển Đông','map-04',21],
 ['hanoi','Miền Bắc','Hoàng thành Thăng Long','Hà Nội','Di tích kinh đô','Đồng bằng và đồi núi','Sông Hồng','map-03',20.99],
 ['haiphong','Miền Bắc','Côn Sơn – Kiếp Bạc','Hải Dương','Di tích lịch sử','Đồng bằng và ven biển','Sông Thái Bình','map-07',20.8],
 ['hungyen','Miền Bắc','Phố Hiến','Hưng Yên','Thương cảng lịch sử','Đồng bằng và ven biển','Sông Hồng','map-05',20.6],
 ['ninhbinh','Miền Bắc','Cố đô Hoa Lư','Ninh Bình','Di tích kinh đô','Đồng bằng và núi đá vôi','Sông Đáy','map-04',20.2],
 ['thanhhoa','Miền Trung','Thành nhà Hồ','Thanh Hóa','Di tích kinh đô','Núi, đồng bằng và biển','Sông Mã','map-04',19.8],
 ['nghean','Miền Trung','Khu di tích Kim Liên','Nghệ An','Di tích lịch sử','Núi, đồng bằng và biển','Sông Lam','map-05',19],
 ['hatinh','Miền Trung','Ngã ba Đồng Lộc','Hà Tĩnh','Di tích chiến tranh','Núi, đồng bằng và biển','Sông La','map-05',18.3],
 ['quangtri','Miền Trung','Thành cổ Quảng Trị','Quảng Trị','Di tích chiến tranh','Núi, đồng bằng và biển','Sông Bến Hải','map-02',17.2],
 ['hue','Miền Trung','Kinh thành Huế','Huế','Di tích kinh đô','Núi, đồng bằng và biển','Sông Hương','map-06',16.4],
 ['danang','Miền Trung','Phố cổ Hội An','Quảng Nam','Thương cảng lịch sử','Núi, đồng bằng và biển','Sông Thu Bồn','map-07',15.9],
 ['quangngai','Miền Trung','Địa điểm khởi nghĩa Ba Tơ','Quảng Ngãi','Di tích cách mạng','Cao nguyên và ven biển','Sông Trà Khúc','map-05',14.8],
 ['gialai','Miền Trung','Bảo tàng Quang Trung','Bình Định','Bảo tàng lịch sử','Cao nguyên và ven biển','Sông Ba','map-05',14],
 ['daklak','Miền Trung','Nhà đày Buôn Ma Thuột','Đắk Lắk','Di tích lịch sử','Cao nguyên và ven biển','Sông Sêrêpốk','map-05',12.8],
 ['khanhhoa','Miền Trung','Tháp Bà Ponagar','Khánh Hòa','Di tích thờ tự','Núi và ven biển','Biển Đông','map-07',12],
 ['lamdong','Miền Trung','Dinh Bảo Đại ở Đà Lạt','Lâm Đồng','Di tích lịch sử','Cao nguyên và ven biển','Sông Đồng Nai','map-05',11.6],
 ['dongnai','Miền Nam','Chiến khu Đ','Đồng Nai','Di tích cách mạng','Đồi thấp và đồng bằng','Sông Đồng Nai','map-05',11.3],
 ['tayninh','Miền Nam','Căn cứ Trung ương Cục miền Nam','Tây Ninh','Di tích cách mạng','Đồng bằng và núi thấp','Sông Vàm Cỏ Đông','map-05',11.1],
 ['hochiminh','Miền Nam','Bến Nhà Rồng','TP. Hồ Chí Minh','Di tích lịch sử','Đồng bằng và ven biển','Sông Sài Gòn','map-08',10.8],
 ['dongthap','Miền Nam','Khu di tích Xẻo Quýt','Đồng Tháp','Di tích cách mạng','Đồng bằng châu thổ','Sông Tiền','map-05',10.4],
 ['vinhlong','Miền Nam','Khu lưu niệm Nguyễn Đình Chiểu','Bến Tre','Di tích danh nhân','Đồng bằng châu thổ','Sông Cổ Chiên','map-05',10.1],
 ['angiang','Miền Nam','Khu di tích Óc Eo','An Giang','Di tích khảo cổ','Đồng bằng, núi và biển','Sông Hậu','map-05',10],
 ['cantho','Miền Nam','Chợ nổi Cái Răng','Cần Thơ','Không gian văn hóa sông nước','Đồng bằng châu thổ','Sông Hậu','map-05',9.8],
 ['camau','Miền Nam','Khu lưu niệm Cao Văn Lầu','Bạc Liêu','Di tích danh nhân','Đồng bằng ven biển','Vịnh Thái Lan','map-05',9.2],
];
export const EXPLORATION_MAPS = rows.map(([id, region, landmark, oldProvince, kind, terrain, water, sceneryMapId, latitude], i) => ({ ...PROVINCES.find(p => p.id === id), number: i + 1, region, landmark, oldProvince, kind, terrain, water, sceneryMapId, latitude, scenery: getProvinceScenery(id) }));
