const climateSource = ['Cục Du lịch Quốc gia Việt Nam · Khí hậu các vùng', 'https://vietnam.travel/things-to-do/weather-and-climate-vietnam'];
export const GEOGRAPHY_LESSONS = {
  'map-01': {
    region: 'Đông Bắc · Miền Bắc',
    location: 'Cao Bằng là tỉnh miền núi phía đông bắc, có biên giới với Trung Quốc. Pác Bó nằm giữa núi đá vôi, hang động và suối. Hãy phân biệt thung lũng thấp với các khối núi cao xung quanh.',
    terrain: 'Địa hình bị chia cắt khiến đường đi quanh co, nhưng thung lũng và suối tạo những nơi thuận lợi hơn cho cư trú. Vị trí biên giới cũng mở ra các tuyến liên lạc qua núi.',
    climate: 'Mùa hè thường nóng, mưa nhiều; mùa đông lạnh và ít mưa hơn. Độ cao và hướng sườn núi làm nhiệt độ khác nhau giữa các nơi, nên không thể coi toàn tỉnh có thời tiết giống hệt nhau.',
    connection: 'Liên hệ Pác Bó: rừng núi và hang động tạo chỗ ở kín đáo; nguồn nước hỗ trợ sinh hoạt. Cùng địa hình đó, mưa lớn lại làm việc đi lại khó hơn. Một yếu tố tự nhiên có thể vừa thuận lợi vừa gây trở ngại.',
    takeaway: 'Nhớ ba từ khóa: biên giới – núi đá vôi – mùa đông lạnh.',
    question: 'Vì sao không nên dùng thời tiết ở một thung lũng để mô tả toàn bộ Cao Bằng?',
    choices: ['Vì độ cao và địa hình tạo khác biệt giữa các nơi', 'Vì toàn tỉnh có khí hậu sa mạc', 'Vì mọi nơi luôn có nhiệt độ bằng nhau'], answer: 0,
    explanation: 'Địa hình phân hóa làm điều kiện nhiệt, ẩm khác nhau. Thời tiết tại một điểm không đại diện hoàn toàn cho cả tỉnh.',
    sources: [['Báo Cao Bằng · Đặc trưng khí hậu', 'https://baocaobang.vn/net-dac-trung-cua-khi-hau-cao-bang-3171078.html']],
  },
  'map-02': {
    region: 'Tây Bắc · Miền Bắc',
    location: 'Điện Biên ở Tây Bắc, giáp Lào và Trung Quốc. Mường Thanh là một lòng chảo: phần đất tương đối bằng phẳng nằm giữa các dãy đồi núi. Sông Nậm Rốm chảy qua không gian này.',
    terrain: 'Đáy thung lũng thuận lợi hơn cho ruộng lúa và điểm dân cư; các sườn núi dốc gây khó khăn cho giao thông. Khi đọc bản đồ, hãy tìm cả đường sông và đường qua đèo, không chỉ nhìn khoảng cách thẳng.',
    climate: 'Mùa đông tương đối lạnh, ít mưa; mùa hạ nóng và mưa nhiều. Khí hậu thay đổi theo địa hình, có thể có những đợt gió tây khô nóng.',
    connection: 'Liên hệ chiến dịch 1954: đồi núi bao quanh lòng chảo tạo vị trí quan sát nhưng cũng khiến vận chuyển khó khăn. Mưa, bùn và đường dốc là những điều kiện phải tính đến trong tiếp tế.',
    takeaway: 'Nhớ: lòng chảo Mường Thanh – núi bao quanh – vận chuyển khó.',
    question: 'Lòng chảo Mường Thanh có đặc điểm nào?',
    choices: ['Đảo san hô ngoài biển', 'Vùng tương đối bằng nằm giữa đồi núi', 'Cao nguyên băng tuyết'], answer: 1,
    explanation: 'Lòng chảo là vùng trũng tương đối bằng phẳng được bao quanh bởi địa hình cao hơn.',
    sources: [['HĐND tỉnh Điện Biên · Địa giới và tự nhiên', 'https://daibieunhandan.dienbien.gov.vn/detail/1035/Dia-gioi-hanh-chinh.html']],
  },
  'map-03': {
    region: 'Đồng bằng sông Hồng · Miền Bắc',
    location: 'Hà Nội gắn với đồng bằng sông Hồng. Địa bàn thành phố có cả vùng đồng bằng và đồi núi phía tây; khu Hoàng thành Thăng Long nằm trong không gian đô thị lịch sử.',
    terrain: 'Sông vận chuyển và bồi tụ phù sa, góp phần tạo đồng bằng. Địa hình thấp, khá bằng giúp giao thông và sản xuất, nhưng cũng cần đê điều, thoát nước khi mưa lớn.',
    climate: 'Mùa hè thường nóng, ẩm, mưa nhiều; mùa đông mát đến lạnh. Thời kỳ chuyển mùa làm thời tiết thay đổi rõ.',
    connection: 'Liên hệ việc dời đô: vị trí trong đồng bằng và các tuyến giao thông giúp Thăng Long kết nối cư dân, hàng hóa. Đây là cách dùng địa lý để hiểu một lựa chọn lịch sử, không phải khẳng định tự nhiên quyết định mọi việc.',
    takeaway: 'Nhớ: sông Hồng – phù sa – trung tâm giao lưu.',
    question: 'Đặc điểm nào hỗ trợ Thăng Long phát triển giao thương?',
    choices: ['Nằm tách biệt hoàn toàn khỏi đường sông', 'Nằm giữa vùng băng giá', 'Kết nối đồng bằng và các tuyến đường sông'], answer: 2,
    explanation: 'Đường sông và đồng bằng giúp kết nối các khu dân cư và vùng sản xuất với đô thị.',
    sources: [climateSource, ['UNESCO · Hoàng thành Thăng Long', 'https://whc.unesco.org/en/list/1328/']],
  },
  'map-04': {
    region: 'Rìa đồng bằng sông Hồng · Miền Bắc',
    location: 'Bài học tập trung vào Hoa Lư – Tràng An thuộc Ninh Bình trước sắp xếp. Nơi đây chuyển tiếp giữa núi đá vôi, đồng bằng và hệ thống sông; tỉnh Ninh Bình mới còn bao gồm Hà Nam và Nam Định cũ.',
    terrain: 'Nước tác động lâu dài lên đá vôi, tạo hang động và cảnh quan karst. Các núi đá nổi lên giữa thung lũng có nước khiến đường đi nhiều nơi phải theo khe núi hoặc dòng sông.',
    climate: 'Khí hậu nhiệt đới gió mùa, có mùa hè nóng ẩm, mưa nhiều và mùa đông lạnh hơn. Lượng mưa thay đổi theo mùa ảnh hưởng mực nước sông, hang và đồng ruộng.',
    connection: 'Liên hệ Hoa Lư: núi đá là vật cản tự nhiên, sông giúp di chuyển và trao đổi. Vì vậy khi tìm hiểu kinh đô, cần nhìn đồng thời địa hình phòng thủ và đường liên lạc.',
    takeaway: 'Nhớ: đá vôi – hang động – kinh đô giữa núi.',
    question: 'Địa hình karst gắn với quá trình nào?',
    choices: ['Nước tác động lâu dài lên đá vôi', 'Băng phủ quanh năm trên đồng bằng', 'Cát biển biến thành núi trong một ngày'], answer: 0,
    explanation: 'Nước hòa tan và xâm thực đá vôi qua thời gian dài, góp phần tạo hang động và địa hình karst.',
    sources: [['Sở KH&ĐT Ninh Bình · Điều kiện tự nhiên (địa bàn cũ)', 'https://dpi.ninhbinh.gov.vn/vi/tong-quan-ninh-binh/21-gioi-thieu-chung-ve-ninh-binh.html'], ['UNESCO · Tràng An', 'https://whc.unesco.org/en/list/1438/']],
  },
  'map-05': {
    region: 'Bắc Trung Bộ · Miền Trung',
    location: 'Nghệ An kéo dài từ vùng núi giáp Lào ở phía tây đến biển ở phía đông. Kim Liên, Nam Đàn gắn với không gian đồng bằng và lưu vực sông Lam.',
    terrain: 'Từ tây xuống đông, địa hình hạ thấp từ núi đến đồng bằng ven biển. Sông mang nước từ thượng nguồn xuống hạ lưu, nên mưa trên núi có thể ảnh hưởng vùng thấp ở xa nơi mưa.',
    climate: 'Mùa hè có thể gặp gió phơn tây nam khô nóng; mưa bão gây khó khăn vào một số thời kỳ trong năm. Không phải mọi ngày hè đều có gió phơn và không phải toàn tỉnh mưa cùng lúc.',
    connection: 'Bài học địa lý: không khí xuống sườn khuất gió bị nén, nóng lên, độ ẩm tương đối giảm. Hiệu ứng phơn giúp giải thích vì sao cùng là miền nhiệt đới nhưng có những đợt nóng khô rất rõ ở xứ Nghệ.',
    takeaway: 'Nhớ: núi – đồng bằng – biển; sông Lam và gió phơn.',
    question: 'Vì sao hạ lưu có thể bị ảnh hưởng khi mưa lớn ở thượng nguồn?',
    choices: ['Nước sông luôn chảy ngược lên núi', 'Nước trong lưu vực tập trung theo sông xuống vùng thấp', 'Mưa chỉ tác động đúng nơi giọt mưa rơi'], answer: 1,
    explanation: 'Các phần trong một lưu vực liên hệ với nhau qua dòng chảy. Vì vậy phải quan sát cả vùng thượng nguồn.',
    sources: [['Sở VHTTDL Nghệ An · Vị trí và tự nhiên', 'https://visitnghean.com/tong-quan-ve-nghe-an/so-vhttdl-nghe-an.html'], ['UBND Nghệ An · Điều kiện tự nhiên Thanh Chương', 'https://datafiles.nghean.gov.vn/nan-ubnd/2926/quantritintuc20254/2.%20TM%20dieu%20chinh%20QH%202030%20TC%20%28500kV%29.pdf']],
  },
  'map-06': {
    region: 'Duyên hải miền Trung',
    location: 'Huế nằm ở miền Trung, có vùng núi phía tây, đồng bằng, đầm phá và biển phía đông. Kinh thành gắn với sông Hương; đây là một hệ thống cảnh quan chứ không chỉ một nhóm cung điện.',
    terrain: 'Khoảng cách từ núi ra biển tương đối ngắn. Nước từ sườn núi xuống đồng bằng có thể tập trung nhanh; cần hiểu quan hệ giữa thượng nguồn, thành phố và vùng cửa sông.',
    climate: 'Mưa thường tập trung về cuối năm; mùa hè thường nóng hơn. Những đợt mưa lớn có thể gây ngập vùng thấp.',
    connection: 'Quan sát bản đồ di tích: dòng sông, hướng núi và mặt bằng công trình cùng tạo nên không gian kinh đô. Khí hậu ẩm cũng đặt ra yêu cầu bảo quản vật liệu và di sản.',
    takeaway: 'Nhớ: sông Hương – kinh đô – mưa cuối năm.',
    question: 'Nhận xét nào phù hợp với khí hậu Huế?',
    choices: ['Quanh năm không có mưa', 'Mọi tháng có lượng mưa bằng nhau', 'Mưa thường tập trung về những tháng cuối năm'], answer: 2,
    explanation: 'Huế có tính mùa rõ; các đợt mưa lớn cuối năm là đặc điểm cần lưu ý khi hiểu cảnh quan và đời sống.',
    sources: [climateSource, ['UNESCO · Quần thể di tích Huế', 'https://whc.unesco.org/en/list/678/']],
  },
  'map-07': {
    region: 'Ven biển miền Trung · Quảng Nam cũ, nay Đà Nẵng',
    location: 'Hội An ở hạ lưu sông Thu Bồn, gần biển. Đây là địa bàn Quảng Nam trước sắp xếp, nay thuộc Đà Nẵng. Vị trí cửa sông nối đường thủy nội địa với tuyến giao thương trên biển.',
    terrain: 'Vùng thấp ven sông thuận tiện lập bến, kho hàng và phố chợ. Đổi lại, đời sống phải thích nghi với nước lên và ngập khi có mưa lớn.',
    climate: 'Thời kỳ cuối năm thường mưa nhiều, có nguy cơ ngập; các tháng hè thường nóng hơn. Mùa cụ thể có thể biến động từng năm.',
    connection: 'Hãy nối ba ý: vị trí cửa sông → tàu thuyền và hàng hóa → gặp gỡ văn hóa. Đồng thời, chính vị trí thấp ven sông làm việc bảo tồn phố cổ phải chú ý ngập lụt.',
    takeaway: 'Nhớ: Thu Bồn – thương cảng – giao thoa văn hóa.',
    question: 'Vị trí ven sông của Hội An tạo ra cả điều gì?',
    choices: ['Thuận lợi giao thương và nguy cơ ngập', 'Chỉ có lợi, không có khó khăn', 'Khí hậu băng giá quanh năm'], answer: 0,
    explanation: 'Cùng một vị trí địa lý có thể đem lại lợi thế kinh tế và rủi ro tự nhiên.',
    sources: [climateSource, ['UNESCO · Phố cổ Hội An', 'https://whc.unesco.org/en/list/948/']],
  },
  'map-08': {
    region: 'Đông Nam Bộ · Miền Nam',
    location: 'Chợ Bến Thành và Bến Nhà Rồng nằm trong đô thị Sài Gòn – TP. Hồ Chí Minh trước sắp xếp. Thành phố mới gồm cả Bình Dương và Bà Rịa - Vũng Tàu cũ; không nên dùng đặc điểm của trung tâm để mô tả toàn địa bàn mới.',
    terrain: 'Hệ thống sông Sài Gòn – Đồng Nai kết nối vùng sản xuất, đô thị và cảng biển. Các khu vực thấp ven sông chịu tác động của cả nước từ thượng nguồn, mưa tại chỗ và thủy triều.',
    climate: 'Nóng quanh năm, thường có mùa mưa khoảng tháng 5–11 và mùa khô khoảng tháng 12–4. Đây là quy luật khái quát, không phải lịch mưa cố định.',
    connection: 'Chợ thể hiện sự tập trung và trao đổi hàng hóa; bến cảng nối đô thị với những hành trình xa. Địa lý đường thủy giúp hiểu vì sao hai địa danh có vai trò khác nhau trong cùng một thành phố.',
    takeaway: 'Nhớ: sông – cảng – chợ; hai mùa mưa, khô.',
    question: '“Chiều nay có mưa ở Bến Nhà Rồng” mô tả điều gì?',
    choices: ['Địa giới hành chính', 'Thời tiết tại một thời điểm, không phải toàn bộ khí hậu', 'Khí hậu bất biến của cả miền Nam'], answer: 1,
    explanation: 'Thời tiết là trạng thái khí quyển trong thời gian ngắn. Khí hậu là đặc điểm được khái quát từ quan sát lâu dài.',
    sources: [climateSource, ['Cục Du lịch Quốc gia Việt Nam · Bến Nhà Rồng', 'https://vietnamtourism.vn/index.php/tourism/items/2925/3']],
  },
};
export const REGION_COMPARISON = [
  ['Miền Bắc', 'Mùa đông lạnh rõ hơn; vùng núi khác với đồng bằng.'],
  ['Miền Trung', 'Địa hình và hướng sườn làm mưa, nóng khác nhau; Huế, Hội An thường mưa muộn hơn miền Bắc.'],
  ['Miền Nam', 'Nền nhiệt cao, tính mùa thường thể hiện rõ qua mùa mưa và mùa khô.'],
];
