export const GRADE_GROUPS = [
  { name: 'Cấp 1', grades: [4, 5] }, { name: 'Cấp 2', grades: [6, 7, 8, 9] }, { name: 'Cấp 3', grades: [10, 11, 12] },
];
export const GRADE_SUMMARIES = {
  4: ['Văn Lang – Âu Lạc: buổi đầu dựng nước.', 'Bắc thuộc và đấu tranh giành độc lập; Bạch Đằng 938.', 'Đinh – Tiền Lê – Lý – Trần – Hậu Lê: xây dựng và bảo vệ đất nước.', 'Tây Sơn và buổi đầu nhà Nguyễn. Khi ôn: nối nhân vật với sự kiện, thời gian và ý nghĩa.'],
  5: ['1858–1945: chống Pháp, các con đường cứu nước và Cách mạng tháng Tám.', '1945–1954: bảo vệ chính quyền, kháng chiến chống Pháp; Điện Biên Phủ.', '1954–1975: xây dựng miền Bắc, đấu tranh thống nhất đất nước.', 'Sau 1975: thống nhất, xây dựng và đổi mới. Học theo trục thời gian, không chỉ nhớ năm.'],
  6: ['Cách tìm hiểu quá khứ và tính thời gian lịch sử.', 'Xã hội nguyên thủy; các quốc gia cổ đại phương Đông và phương Tây.', 'Văn Lang – Âu Lạc, đời sống cư dân và thành Cổ Loa.', 'Thời Bắc thuộc, các cuộc đấu tranh và chiến thắng Bạch Đằng 938.'],
  7: ['Xã hội phong kiến ở châu Âu, phương Đông và Đông Nam Á.', 'Việt Nam từ thế kỉ X: Ngô, Đinh, Tiền Lê, Lý, Trần và Hồ.', 'Lam Sơn, Đại Việt thời Lê sơ; biến động thế kỉ XVI–XVIII, phong trào Tây Sơn.', 'Việt Nam nửa đầu thế kỉ XIX. So sánh chính trị, kinh tế và văn hóa từng thời kỳ.'],
  8: ['Thế giới cận đại: cách mạng tư sản, công nghiệp và phong trào công nhân.', 'Châu Á trước sự xâm lược của chủ nghĩa thực dân; hai cuộc chiến tranh thế giới.', 'Cách mạng Nga 1917 và thế giới giữa hai cuộc chiến tranh.', 'Việt Nam 1858–1918: chống Pháp, Cần Vương, Yên Thế và xu hướng cứu nước mới.'],
  9: ['Thế giới từ 1945: Liên Xô, giải phóng dân tộc, Mỹ, Nhật, Tây Âu và quan hệ quốc tế.', 'Việt Nam 1919–1945: phong trào dân tộc, thành lập Đảng và giành chính quyền.', '1945–1975: kháng chiến chống Pháp, chống Mỹ và thống nhất.', 'Sau 1975: xây dựng đất nước và đổi mới. Phân biệt nguyên nhân, diễn biến, kết quả, ý nghĩa.'],
  10: ['Thế giới nguyên thủy, cổ đại, trung đại; văn minh phương Đông và phương Tây.', 'Việt Nam từ nguồn gốc đến giữa thế kỉ XIX: dựng nước, giữ nước, kinh tế và văn hóa.', 'Thế giới cận đại: cách mạng tư sản, công nghiệp, phong trào công nhân.', 'Ôn bằng bảng so sánh xã hội, thể chế và phương thức sản xuất qua từng giai đoạn.'],
  11: ['Thế giới cận đại cuối thế kỉ XIX – đầu XX: các nước châu Á và Chiến tranh thế giới thứ nhất.', 'Cách mạng Nga, thế giới 1918–1939 và Chiến tranh thế giới thứ hai.', 'Việt Nam 1858–1918: kháng chiến chống Pháp và các phong trào yêu nước.', 'So sánh xu hướng bạo động, cải cách và hướng đi của Nguyễn Tất Thành.'],
  12: ['1945–2000: trật tự thế giới, giải phóng dân tộc, Chiến tranh lạnh và xu thế hợp tác.', '1919–1930: chuyển biến xã hội Việt Nam, hoạt động Nguyễn Ái Quốc và thành lập Đảng.', '1930–1945: các phong trào cách mạng, chuẩn bị và giành chính quyền.', '1945–1954: bảo vệ chính quyền và kháng chiến chống Pháp.', '1954–1975: hai nhiệm vụ chiến lược ở hai miền, thống nhất đất nước.', '1975–2000: xây dựng đất nước và đổi mới. Ghi nhớ quan hệ nguyên nhân – kết quả, tránh học rời từng mốc.'],
};
export const LEARNING_NOTICE = 'Chỉ dùng SGK chương trình trước 2018 và đề kiểm tra chính thức của trường, Sở hoặc Bộ. Mỗi câu phải có tài liệu gốc và vị trí đối chiếu; tách riêng lớp và môn.';
